# Generated by Django 3.0.8 on 2020-08-10 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('bio', models.TextField(max_length=500)),
                ('age', models.IntegerField(null=True)),
                ('location', models.CharField(max_length=30, null=True)),
                ('balance', models.FloatField(null=True)),
                ('profile_image', models.ImageField(null=True, upload_to='users/profile_images')),
                ('facebook_profile', models.URLField(null=True)),
                ('instagram_profile', models.URLField(null=True)),
                ('pinterest_profile', models.URLField(null=True)),
                ('youtube_profile', models.URLField(null=True)),
                ('twitter_profile', models.URLField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
