# Generated by Django 3.0.8 on 2020-08-13 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='details',
            name='bio',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
